<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>android.view.View (2)</name>
   <tag></tag>
   <elementGuidId>ddd6dfa0-d24c-4bcd-aa3b-e4bb90c8e5b6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
      <webElementGuid>46c2fc93-e2de-46ec-b834-14aef774e07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>07eae970-cf40-4afb-b777-9781b812df40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.greyorange.gstore.qa</value>
      <webElementGuid>3178db01-1156-4cd9-8f7b-add21b1690ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>ID # 0984692 002
3-PACK REGULAR COTTON T-SHIRTS
€59.00
x12
Color: 
Black</value>
      <webElementGuid>ea48e719-ddc5-49c2-be57-9d45ff2becf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f75b374-5829-4def-9608-b62656cc45df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9c2c5fc-b579-4f93-af66-bf7a90e152ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d81ee86-2ec1-47f2-a541-f0fcad20d855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b029d4b8-80ac-4887-9cd6-fe8abc47632a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>840eae40-7829-4654-8dac-8c471441d9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9153ae8a-d2cc-4fdb-a651-640c1687db4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a25eb55-ff5d-470e-b3dc-d06448bf97ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b8da43b-283a-4c46-8808-442a8710d5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb190629-9c70-4809-ab1a-5887801abd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81cd2cf9-7d5a-4cf9-8b6e-f6c91e5fd5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>48adb11a-f4cf-42ab-af8f-e2dd762b7cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>774</value>
      <webElementGuid>93762d64-08dc-4a1d-bb56-d7d82cd3d7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1224</value>
      <webElementGuid>7378cbb7-9a9e-4493-b86c-54f2fec82f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>7cffd99c-aa2c-4ac9-a4d5-41128b5d166b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[60,774][1284,1374]</value>
      <webElementGuid>b1ad093b-39d8-4997-a9c7-7d2884213eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33019f8c-e167-446b-85e8-1e40d075497e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2c73af0b-6d6c-4bf8-aa7f-5d9ffcdfed30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>196f567a-83eb-44d2-8b76-b5e3ff744ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[2]/android.view.View[1]/android.view.View[1]/android.view.View[2]/android.widget.ScrollView[1]/android.view.View[3]</value>
      <webElementGuid>0593bbc0-b899-47ae-a4a1-da9c6fa11a25</webElementGuid>
   </webElementProperties>
   <locator>(.//*[@class='android.widget.ImageView'])[2]</locator>
   <locatorCollection>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>NAME</key>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@content-desc = 'ID # 0984692 002
3-PACK REGULAR COTTON T-SHIRTS
€59.00
x12
Color: 
Black']</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**[`enabled == 1`]</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>(.//*[@class='android.widget.ImageView'])[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[2]/android.view.View[1]/android.view.View[1]/android.view.View[2]/android.widget.ScrollView[1]/android.view.View[3]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().className(&quot;android.view.View&quot;).description(&quot;ID # 0984692 002
3-PACK REGULAR COTTON T-SHIRTS
€59.00
x12
Color: 
Black&quot;).resourceId(&quot;&quot;).packageName(&quot;com.greyorange.gstore.qa&quot;).enabled(true).clickable(true).longClickable(false).checkable(false).checked(false).focusable(true).focused(false).scrollable(false).selected(false).index(3)</value>
      </entry>
      <entry>
         <key>ID</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>enabled == 1</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>ID # 0984692 002
3-PACK REGULAR COTTON T-SHIRTS
€59.00
x12
Color: 
Black</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>CLASS_NAME</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
